version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: "/"
    groups:
      docker:
        patterns:
          - "*"
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /source/lib/librdkafka-2.10.1/packaging/nuget
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /source/lib/librdkafka-2.10.1/packaging/tools
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /source/lib/librdkafka-2.10.1/tests
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /source/lib/librdkafka-2.10.1/tests/tools/stats
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /source/lib/lwrb/docs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/lib/nghttp2-1.65.0
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/lib/nghttp2-1.65.0/third-party/mruby
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /source/lib/nghttp2-1.65.0/third-party/mruby
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/lib/rocksdb/build_tools/ubuntu20_image
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /source/lib/rocksdb/docs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/lib/rocksdb/tools
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/lib/zstd-1.5.7/contrib/docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/almalinux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/amazonlinux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/azurelinux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/centos/6
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/centos/7
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/centos
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/debian
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/mariner
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/rockylinux
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/suse
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /source/packaging/distros/ubuntu
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /source/plugins/filter_geoip2/libmaxminddb-1.12.2/t/maxmind-db
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /source/tests/runtime/wasm/go
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /source/tests/runtime/wasm/rust/filter_rust_mp
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /testing
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /source/lib/rocksdb/java/jmh
    schedule:
      interval: daily
