service:
  flush: 1
  log_level: info
  http_server: on
  storage.metrics: on
  health_check: on
pipeline:
  inputs:
    - name: tail
      alias: input_tail_k8s
      path: /var/log/containers/*.log
      tag: kube.*
      multiline.parser: docker, cri
      # Ensure you can write to this as the current user - usually requires a security context
      db: /var/log/fluent-bit.db
      processors:
        logs:
          - name: kubernetes
            kube_tag_prefix: kube.var.log.containers.
  outputs:
      - name: stdout
        alias: output_stdout_all
        match: "*"
