name: Workflow to sync our fork with upstream regularly
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:
    inputs:
      force-push:
        description: 'Trigger a force-push of tags to the fork (default: false), useful if tags were moved upstream'
        type: boolean
        required: false
        default: false
jobs:
  sync_fork:
    name: Sync Fork with Upstream
    # This job syncs the forked repository with the upstream repository
    # It uses the GitHub CLI to sync the fork and push any new tags
    # It requires a GitHub Personal Access Token (PAT) stored in GCP Secret Manager
    # The PAT is retrieved using the google-github-actions/get-secretmanager-secrets action
    # The job runs on an Ubuntu runner and uses the google-github-actions/auth action to authenticate with GCP
    # The GCP service account must have the necessary permissions to access the Secret Manager
    # The job also checks out the forked repository and ensures that all tags are pulled from the upstream repository
    # Finally, it pushes any new tags from the upstream repository to the forked repository
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes to the fork
      # Required for GCP authentication and secret retrieval
      id-token: write
    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/841522437311/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "terraform-infra@infrastructure-464010.iam.gserviceaccount.com"
          create_credentials_file: true
          export_environment_variables: true

      - id: get-secrets
        name: Get secrets from GCP Secret Manager
        # This step retrieves secrets from GCP Secret Manager and sets them as outputs
        # The secrets can then be accessed in subsequent steps using ${{ steps.get-secrets.outputs.<secret_name> }}
        uses: "google-github-actions/get-secretmanager-secrets@v3"
        with:
          secrets: |-
            github-pat:projects/626836145334/secrets/GITHUB_CI_PAT

      - name: Sync fork with upstream
        run: |
          gh repo sync FluentDo/fluent-bit -b master
          gh repo sync FluentDo/fluent-bit -b 4.0
        shell: bash
        env:
          GH_TOKEN: ${{ steps.get-secrets.outputs.github-pat }}

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: FluentDo/fluent-bit
          fetch-depth: 0
          token: ${{ steps.get-secrets.outputs.github-pat }}

      - name: Ensure we pull tags from upstream OSS
        run: |
          git fetch --tags https://github.com/fluent/fluent-bit.git
        shell: bash

      - name: Push upstream tags to fork
        run: git push --tags origin ${{ github.event.inputs.force-push && '--force' || '' }}
        shell: bash
